id: P87AE4906
initial_creation_type: input
source_metadata:
  title: Lama Rigdzin Nyima Series
  language: bo
  description: Texts by Lama Rigdzin Nyima (rig 'dzin nyi ma, b. 1931), a tertön from
    Golok.
  volume:
    a569679bc3cf4d26990db9779f4f2607:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T00:33:40.754315'
last_modified_at: '2022-03-01T00:33:40.754319'
